all:
	g++ lab9.cpp -o lab9.out -I/usr/csshare/pkgs/glew-1.13.0/include -L/usr/csshare/pkgs/glew-1.13.0/lib64/ -I/usr/csshare/pkgs/glfw-3/include -L/usr/csshare/pkgs/glfw-3/lib -lglfw3 -lGLEW -lpthread -lXrandr -lXi -lXxf86vm -lXinerama -lXcursor -lrt

clean:
	rm lab9.out

